"""Pioneer AVR commands."""

from .const import Zone
from .decoders.amp import COMMANDS_AMP
from .decoders.audio import COMMANDS_AUDIO
from .decoders.code_map import CodeMapBase
from .decoders.dsp import COMMANDS_DSP
from .decoders.system import COMMANDS_SYSTEM
from .decoders.tuner import COMMANDS_TUNER
from .decoders.video import COMMANDS_VIDEO

PIONEER_COMMANDS: dict[
    str, dict[Zone | str, str | list[str] | list[type[CodeMapBase]]]
] = {
    **COMMANDS_AMP,
    **COMMANDS_SYSTEM,
    **COMMANDS_DSP,
    **COMMANDS_AUDIO,
    **COMMANDS_TUNER,
    **COMMANDS_VIDEO,
    ## operation ipod
    "ipod_play": {Zone.Z1: ["00IP", "IP"]},
    "ipod_pause": {Zone.Z1: ["01IP", "IP"]},
    "ipod_stop": {Zone.Z1: ["02IP", "IP"]},
    "ipod_previous": {Zone.Z1: ["03IP", "IP"]},
    "ipod_next": {Zone.Z1: ["04IP", "IP"]},
    "ipod_rewind": {Zone.Z1: ["05IP", "IP"]},
    "ipod_fastforward": {Zone.Z1: ["06IP", "IP"]},
    "ipod_repeat": {Zone.Z1: ["07IP", "IP"]},
    "ipod_shuffle": {Zone.Z1: ["08IP", "IP"]},
    "ipod_display": {Zone.Z1: ["09IP", "IP"]},
    "ipod_control": {Zone.Z1: ["10IP", "IP"]},
    "ipod_cursor_up": {Zone.Z1: ["13IP", "IP"]},
    "ipod_cursor_down": {Zone.Z1: ["14IP", "IP"]},
    "ipod_cursor_right": {Zone.Z1: ["15IP", "IP"]},
    "ipod_cursor_left": {Zone.Z1: ["16IP", "IP"]},
    "ipod_enter": {Zone.Z1: ["17IP", "IP"]},
    "ipod_return": {Zone.Z1: ["18IP", "IP"]},
    "ipod_top_menu": {Zone.Z1: ["19IP", "IP"]},
    "ipod_iphone_direct_control": {Zone.Z1: ["20IP", "IP"]},
    ## operation network
    "network_numeric_0": {Zone.Z1: ["00NW", "NW"]},
    "network_numeric_1": {Zone.Z1: ["01NW", "NW"]},
    "network_numeric_2": {Zone.Z1: ["02NW", "NW"]},
    "network_numeric_3": {Zone.Z1: ["03NW", "NW"]},
    "network_numeric_4": {Zone.Z1: ["04NW", "NW"]},
    "network_numeric_5": {Zone.Z1: ["05NW", "NW"]},
    "network_numeric_6": {Zone.Z1: ["06NW", "NW"]},
    "network_numeric_7": {Zone.Z1: ["07NW", "NW"]},
    "network_numeric_8": {Zone.Z1: ["08NW", "NW"]},
    "network_numeric_9": {Zone.Z1: ["09NW", "NW"]},
    "network_play": {Zone.Z1: ["10NW", "NW"]},
    "network_pause": {Zone.Z1: ["11NW", "NW"]},
    "network_previous": {Zone.Z1: ["12NW", "NW"]},
    "network_next": {Zone.Z1: ["13NW", "NW"]},
    "network_rewind": {Zone.Z1: ["14NW", "NW"]},
    "network_fastforward": {Zone.Z1: ["15NW", "NW"]},
    "network_display": {Zone.Z1: ["18NW", "NW"]},
    "network_stop": {Zone.Z1: ["20NW", "NW"]},
    "network_up": {Zone.Z1: ["26NW", "NW"]},
    "network_down": {Zone.Z1: ["27NW", "NW"]},
    "network_right": {Zone.Z1: ["28NW", "NW"]},
    "network_left": {Zone.Z1: ["29NW", "NW"]},
    "network_enter": {Zone.Z1: ["30NW", "NW"]},
    "network_return": {Zone.Z1: ["31NW", "NW"]},
    "network_program": {Zone.Z1: ["32NW", "NW"]},
    "network_clear": {Zone.Z1: ["33NW", "NW"]},
    "network_repeat": {Zone.Z1: ["34NW", "NW"]},
    "network_random": {Zone.Z1: ["35NW", "NW"]},
    "network_menu": {Zone.Z1: ["36NW", "NW"]},
    "network_edit": {Zone.Z1: ["37NW", "NW"]},
    "network_class": {Zone.Z1: ["38NW", "NW"]},
    ## operation adapterport/BT
    "operation_adapaterport_play_pause": {Zone.Z1: ["20BT", "BT"]},
    "operation_adapaterport_play": {Zone.Z1: ["10BT", "BT"]},
    "operation_adapaterport_pause": {Zone.Z1: ["11BT", "BT"]},
    "operation_adapaterport_stop": {Zone.Z1: ["12BT", "BT"]},
    "operation_adapaterport_previous": {Zone.Z1: ["13BT", "BT"]},
    "operation_adapaterport_next": {Zone.Z1: ["14BT", "BT"]},
    "operation_adapaterport_rewind": {Zone.Z1: ["15BT", "BT"]},
    "operation_adapaterport_fastforward": {Zone.Z1: ["16BT", "BT"]},
    "operation_adapaterport_repeat": {Zone.Z1: ["17BT", "BT"]},
    "operation_adapaterport_random": {Zone.Z1: ["18BT", "BT"]},
    "operation_adapaterport_display": {Zone.Z1: ["19BT", "BT"]},
    "operation_adapaterport_cursor_up": {Zone.Z1: ["21BT", "BT"]},
    "operation_adapaterport_cursor_down": {Zone.Z1: ["22BT", "BT"]},
    "operation_adapaterport_cursor_right": {Zone.Z1: ["23BT", "BT"]},
    "operation_adapaterport_cursor_left": {Zone.Z1: ["24BT", "BT"]},
    "operation_adapaterport_enter": {Zone.Z1: ["25BT", "BT"]},
    "operation_adapaterport_return": {Zone.Z1: ["26BT", "BT"]},
    "operation_adapaterport_top_menu": {Zone.Z1: ["27BT", "BT"]},
    "operation_adapaterport_sound_retriever_air": {Zone.Z1: ["28BT", "BT"]},
    ## operation mhl
    "mhl_select": {Zone.Z1: ["00MHL", "MHL"]},
    "mhl_up": {Zone.Z1: ["01MHL", "MHL"]},
    "mhl_down": {Zone.Z1: ["02MHL", "MHL"]},
    "mhl_left": {Zone.Z1: ["03MHL", "MHL"]},
    "mhl_right": {Zone.Z1: ["04MHL", "MHL"]},
    "mhl_root_menu": {Zone.Z1: ["05MHL", "MHL"]},
    "mhl_exit": {Zone.Z1: ["06MHL", "MHL"]},
    "mhl_numeric_0": {Zone.Z1: ["07MHL", "MHL"]},
    "mhl_numeric_1": {Zone.Z1: ["08MHL", "MHL"]},
    "mhl_numeric_2": {Zone.Z1: ["09MHL", "MHL"]},
    "mhl_numeric_3": {Zone.Z1: ["10MHL", "MHL"]},
    "mhl_numeric_4": {Zone.Z1: ["11MHL", "MHL"]},
    "mhl_numeric_5": {Zone.Z1: ["12MHL", "MHL"]},
    "mhl_numeric_6": {Zone.Z1: ["13MHL", "MHL"]},
    "mhl_numeric_7": {Zone.Z1: ["14MHL", "MHL"]},
    "mhl_numeric_8": {Zone.Z1: ["15MHL", "MHL"]},
    "mhl_numeric_9": {Zone.Z1: ["16MHL", "MHL"]},
    "mhl_enter": {Zone.Z1: ["17MHL", "MHL"]},
    "mhl_clear": {Zone.Z1: ["18MHL", "MHL"]},
    "mhl_channel_up": {Zone.Z1: ["19MHL", "MHL"]},
    "mhl_channel_down": {Zone.Z1: ["20MHL", "MHL"]},
    "mhl_previous_channel": {Zone.Z1: ["21MHL", "MHL"]},
    "mhl_sound_select": {Zone.Z1: ["22MHL", "MHL"]},
    "mhl_play": {Zone.Z1: ["23MHL", "MHL"]},
    "mhl_stop": {Zone.Z1: ["24MHL", "MHL"]},
    "mhl_pause": {Zone.Z1: ["25MHL", "MHL"]},
    "mhl_record": {Zone.Z1: ["26MHL", "MHL"]},
    "mhl_rewind": {Zone.Z1: ["27MHL", "MHL"]},
    "mhl_fastforward": {Zone.Z1: ["28MHL", "MHL"]},
    "mhl_eject": {Zone.Z1: ["29MHL", "MHL"]},
    "mhl_next": {Zone.Z1: ["30MHL", "MHL"]},
    "mhl_previous": {Zone.Z1: ["31MHL", "MHL"]},
    "mhl_play_function": {Zone.Z1: ["32MHL", "MHL"]},
    "mhl_pause_play_function": {Zone.Z1: ["33MHL", "MHL"]},
    "mhl_record_function": {Zone.Z1: ["34MHL", "MHL"]},
    "mhl_pause_record_function": {Zone.Z1: ["35MHL", "MHL"]},
    "mhl_stop_function": {Zone.Z1: ["36MHL", "MHL"]},
    "mhl_show_information": {Zone.Z1: ["37MHL", "MHL"]},
    ## operation amp
    "operation_amp_status_display": {Zone.Z1: "STS"},
    "operation_amp_cursor_up": {Zone.Z1: "CUP"},
    "operation_amp_cursor_down": {Zone.Z1: "CDN"},
    "operation_amp_cursor_right": {Zone.Z1: "CRI"},
    "operation_amp_cursor_left": {Zone.Z1: "CLE"},
    "operation_amp_cursor_enter": {Zone.Z1: "CEN"},
    "operation_amp_cursor_return": {Zone.Z1: "CRT"},
    "operation_amp_audio_parameter": {Zone.Z1: "ATA"},
    "operation_amp_output_parameter": {Zone.Z1: "HPA"},
    "operation_amp_video_parameter": {Zone.Z1: "VPA"},
    "operation_amp_channel_select": {Zone.Z1: "CLC"},
    "operation_amp_home_menu": {Zone.Z1: "HM"},
    "operation_amp_key_off": {Zone.Z1: "KOF"},
}
